### ISSUE TITLE
Please upload the binaries to GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [KarlZeilhofer/kicad-appimage#1]
Please upload the binaries to your [GitHub Releases](https://github.com/KarlZeilhofer/kicad-appimage/releases) rather than into your git repository.

More information:
https://help.github.com/articles/creating-releases/

**Comment by KarlZeilhofer** [comment]
Thanks for that hint, I'm not used to releases. Does it add any benefit in this case, where source code isn't related anyway?

**Comment by probonopd** [comment]
Yes, it adds the benefit to be an easy to find location for downloading the binaries.

**Comment by probonopd** [comment]
By the way, a big __thank you__ for making the AppImages :+1:

**Comment by KarlZeilhofer** [comment]
I think, I have to replace the repo by the recipes only, and upload the AppImages to the releases, right?

**Comment by probonopd** [comment]
Correct

**Comment by KarlZeilhofer** [comment]
Done

**Comment by probonopd** [comment]
Thank you.
